# # ---------------------------
# # Imagen para levantar Storybook en modo desarrollo
# # ---------------------------

# ---------------------------
# Etapa de construcción (builder)
# ---------------------------
FROM node:23.6.1-alpine3.21 AS dev-builder

# 1. Instalar herramientas como root
RUN apk add --no-cache \
    curl \
    git \
    bash \
    openssh-client \
    && rm -rf /var/cache/apk/*

# 2. Configurar Corepack primero como root
RUN corepack enable && corepack prepare yarn@latest --activate

# Configurar entorno de desarrollo
WORKDIR /app

# Variables de entorno para registros privados
ARG NPM_GITHUB_TOKEN
ARG FONTAWESOME_TOKEN

# Convierte los ARGs en ENV para que Yarn las use durante el build
ENV NPM_GITHUB_TOKEN=$NPM_GITHUB_TOKEN
ENV FONTAWESOME_TOKEN=$FONTAWESOME_TOKEN

# Configurar Yarn
COPY .yarnrc.yml ./

# Copiar dependencias primero para cache eficiente
COPY package.json ./

# Instalar dependencias con cache
RUN corepack use yarn@latest

# ---------------------------
# Etapa final de desarrollo
# ---------------------------
FROM dev-builder AS development

COPY --from=dev-builder /app/node_modules ./node_modules

# Copiar código fuente
COPY . .

# Puertos y salud
EXPOSE 6006
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s CMD curl --fail http://localhost:6006 || exit 1

# Comando principal con hot-reload
CMD ["yarn", "storybook"]