// prefijo FAL
export {
  faTimes,
  faCopy,
  faCalendarAlt,
  faLongArrowRight,
  faArrowLeft,
  faArrowRight,
  faCloudDownloadAlt,
  faAngleDown,
  faClock,
  faMinus,
  faEquals,
  faDivide,
  faExclamation,
  faMoneyBillWave,
  faHomeLgAlt,
  faSack,
  faCoins,
  faReceipt,
  faHandHoldingUsd,
} from '@fortawesome/pro-light-svg-icons';
