// prefijo fas
export {
  faUserSecret,
  faHome,
  faPaperPlane,
  faTicketAlt,
  faWallet,
  faGift,
  faQuestionCircle,
  faInfoCircle,
  faUserPlus,
  faUserTimes,
  faTimesCircle,
  faCheckCircle,
  faFileSignature,
  faEdit,
  faTrash,
  faPlusCircle,
  faMinusCircle,
  faDivide,
  faChevronRight,
  faChevronLeft,
  faMoneyBillWave,
  faLongArrowAltLeft,
  faFileInvoiceDollar,
  faUndoAlt,
  faCreditCard,
  faEllipsisV,
  faBullhorn,
  faFileAlt,
  faMars,
  faVenus,
  faUsers,
  faBuilding,
  faMoneyCheckAlt,
  faLock,
  faQuestion,
  faAngleDown as fasAngleDown,
  faDownload as fasDownload,
  faSearch as fasSearch,
  faUniversity as fasUniversity,
  faPencilAlt as fasPencilAlt,
  faSave,
  faFileExcel as fasFileExcel,
  faUserSlash,
  faExclamationTriangle,
  faDollarSign as fasDollarSign,
  faArrowRight as fasArrowRight,
  faHandHoldingUsd as fasHandHoldingUsd,
  faSort,
  faTrashAlt,
  faCaretDown,
  faClock,
  faBars,
  faStore,
  faArrowUpFromBracket
} from '@fortawesome/free-solid-svg-icons';
